version: "3.9"

services:
  app:
    build: .
    container_name: Goldencare
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 987654321
      DB_NAME: rawat_kasih
    restart: always

  db:
    image: postgres:15
    container_name: Goldencare-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 987654321
      POSTGRES_DB: rawat_kasih
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: